// <auto-generated />
namespace Antra.Training.Contoso.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NullableEnrollmentDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableEnrollmentDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201802192326322_NullableEnrollmentDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
